name: PlaceReminder
version: '${project.version}'
main: com.che1sBukkit.BlockReminder.Main
api-version: '1.20'
permission:
  bypass.test1:
    default: op
    description: Permission for skipping reminding